### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by AlanYe-Dev** [pionxzh/Get-Twitter-Icons-Back#10]
Thanks for the amazing project! However, I've met some issues and I would like to list some suggestions for this userscript.

1. Replace "**on X**" to "**on Twitter**" in<title> on Tweets (Posts)
<img width="400" alt="image" src="https://github.com/pionxzh/Get-Twitter-Icons-Back/assets/45558679/351267d9-b736-4747-b646-991969caa6bf">

2. Recover several string texts to the original (Twitter) ones.

Examples:
- Premium -> Blue
- Post -> Tweet
- etc.

Anyway, thanks for the project~

**Comment by pionxzh** [comment]
Thanks. I think the first one is a good idea. And  I will consider the viability of 2.

**Comment by pionxzh** [comment]
1. Title replacement has been enhanced, including the case mentioned.
2. Twitter Blue's icon and text are restored.
3. Other texts won't be replaced and would be considered out of the scope unless it's really annoying.

![image](https://github.com/pionxzh/Get-Twitter-Icons-Back/assets/9910706/7a090e99-4c75-45e5-9446-de4c5bb7d92f)

**Comment by pionxzh** [comment]
released in v1.8.0
