### ISSUE TITLE
Bird icon is black and not blue

### ISSUE THREAD

**Issue by lonestaritaly** [pionxzh/Get-Twitter-Icons-Back#7]
Since a couple of days now the bird icon on top of left sidebar is black and no longer blue.
is this expected?
(happens with 1.6.0)

![immagine](https://github.com/pionxzh/Get-Twitter-Icons-Back/assets/1325475/2e9925bc-5764-4ba9-b5c8-1641e407c821)

**Comment by pionxzh** [comment]
May I know your browser and the language on twitter?

**Comment by pionxzh** [comment]
It seems like I have used a few syntax that is not supported by safari 16.4- and other older browser.

**Comment by lonestaritaly** [comment]
> May I know your browser and the language on twitter?

Firefox 115 on Linux
it's the same also with latest Chrome on Linux

**Comment by pionxzh** [comment]
@lonestaritaly I have released [v1.6.1](https://github.com/pionxzh/Get-Twitter-Icons-Back/releases/tag/v1.6.1) which should works in most of the browsers. Can you verify?

**Comment by lonestaritaly** [comment]
> @lonestaritaly I have released [v1.6.1](https://github.com/pionxzh/Get-Twitter-Icons-Back/releases/tag/v1.6.1) which should works in most of the browsers. Can you verify?

Yes now it's blue again. Thank you very much!
