### ISSUE TITLE
Mobile support?

### ISSUE THREAD

**Issue by Chudesnov** [pionxzh/Get-Twitter-Icons-Back#9]
Thanks for working on this project! I noticed that while it works with the desktop Twitter version, installing it using the Userscripts app on iOS doesn't change any icons in the mobile web UI (only the color of the X icon). Are you willing to accept a patch that would enable cross-platform support, or would it be out of scope?

**Comment by pionxzh** [comment]
Sure, PR's welcome. 👍

**Comment by pionxzh** [comment]
I just double-checked, seems it works on mobile without a problem. All icons are replaced successfully. Not sure what the actual issue. 🤔

**Comment by Chudesnov** [comment]
With Userscripts extension for iOS Safari it only partially works. Page title is replaced but icons are not
![IMG_1989](https://github.com/pionxzh/Get-Twitter-Icons-Back/assets/240422/d3774e1f-a249-4be5-9f61-90add1ee1b70)
![IMG_1988](https://github.com/pionxzh/Get-Twitter-Icons-Back/assets/240422/a9c75eeb-7b80-4a64-88d2-56e3a2e64224)

**Comment by Chudesnov** [comment]
Looks like it might be more of an issue with Userscripts API rather than mobile vs desktop. I’ll take a look later when I have access to a Mac to inspect the script

**Comment by pionxzh** [comment]
Oh, might be related to the css injection I guess.

**Comment by pionxzh** [comment]
@Chudesnov Any update?

**Comment by pionxzh** [comment]
closing first. Let me know if you have new findings!
